import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ListItem from 'components/listItem'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>FoodFinder</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <ListItem />
        </main>
      </div>
    </>
  )
}

export default Home
